- rmbox/rmbox.c
Add missing trace class to the rmbox to avoid unknow value message.
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>
> rmbox: add missing trace class to sync with firmware

- test/src_run.sh
The topology files naming has been updated to include mclk-N so it
needs to be added here as well for the script src_run.sh to work.
> SOFT: Fix the topology file name in SRC test topology lookup

- topology/sof/pipe-src-playback.m4
This patch increases the SRC source buffer to contain 5 periods of data
(measured for 1 ms @ 48 kHz ). It fixes the issue in 176.4 kHz to 48 kHz
playback conversion that the pipeline freezes with insufficient available
data in source buffer for SRC to convert and too little free in buffer
for host to fill another 48 frames.
176.4 kHz playback is currently the largest buffer size consumer due
to non-steady in/out rate. The higher rate conversion 192 kHz to 48 kHz
can operate with smaller size buffer due to steady in/out rate.
Note: This has been only simulated in the host test bench since SRC
playback does not run currently in real devices due to another issue.
However since buffers simulation is accurate this should be a real issue.
Signed-off-by: Seppo Ingalsuo …
> SOFT: Increase SRC playback topology buffer size

- test/test_utils/chirp_test_analyze.m
- test/test_utils/chirp_test_input.m
- test/test_utils/find_test_signal.m
- test/test_utils/mix_chirp.m
- test/test_utils/mix_sweep.m
The audio tests signals contain a start and end marker to extract the
test output to analyze from in-between the markers.
This patch fixes a fail in SRC tests that was caused by incorrect
synchronization to output data. The chirp upper frequency is limited
to 0.99 x Nyquist frequency since the Nyquist frequency in the end
aliased and caused a visible artefact to spectral plot and it triggered
a resampler filter impulse response that had some correlation with
start/end marker chirps. The cosine chirp initialization to start from
90 degrees (zero PCM code instead of max.) also cleaned the start impulse
and improved the look of spectrogram plot.
The syncronization was limited to seek from one measured channel only. The
sync finder also didn't handle properly multi-channel input.
The output …
> SOFT: Improve audio test synchronization code

- topology/sof-byt-nocodec.m4
Set dai id number according to NoCodec-id
Signed-off-by: Rander Wang <rander.wang@linux.intel.com>
> SOFT: fix this topology failed to be loaded

- kmod_scripts/sof_insert.sh
- kmod_scripts/sof_remove.sh
Update module names, only unload what is loaded and add pcm512x
support for Up^2 board.
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> kmod_scripts: clean-up and add pcm512x support

- topology/Makefile.am
- topology/platform/intel/icl.m4
- topology/sof-icl-nocodec.m4
Test it on ICL
Signed-off-by: Rander Wang <rander.wang@linux.intel.com>
> tplg: add nocodec topology for icelake

- topology/sof-apl-nocodec.m4
For some reason parts of the topology were commented out.  Make sure
all 6 SSPs are enabled.
Tested on Up2 with a LogicPro-based check on SSP5 (only interface
accessive on the HAT connector)
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> topology: sof-apl-nocodec: enable all 6 SSPs

- topology/Makefile.am
copy/paste mistake
Fixes: 3dd17dc0 ('dist: fix make dist for topology M4')
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> topology: fix Makefile.am

- topology/m4/dai.m4
Previously it was set to be the dai index which works if there's
only one type of BE DAI's.
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
> topology: fix BE DAI id to be set to ID (not index)

- tune/eq/eq_align.m
- tune/eq/eq_alsactl_write.m
- tune/eq/eq_blob_write.m
- tune/eq/eq_coef_quant.m
- tune/eq/eq_compute.m
- tune/eq/eq_compute_response.m
- tune/eq/eq_compute_tot_response.m
- tune/eq/eq_defaults.m
- tune/eq/eq_define_parametric_eq.m
- tune/eq/eq_fir_blob_merge.m
- tune/eq/eq_fir_blob_pack.m
- tune/eq/eq_fir_blob_quant.m
- tune/eq/eq_iir_blob_merge.m
- tune/eq/eq_iir_blob_pack.m
- tune/eq/eq_iir_blob_quant.m
- tune/eq/eq_norm.m
- tune/eq/eq_plot.m
- tune/eq/example_fir_eq.m
- tune/eq/example_iir_eq.m
- tune/eq/example_spk_eq.m
This patch adds support to SOFT to setup FIR and IIR equalizer types.
The examples scripts for simple FIR loudness effect, IIR loudness effect
and speaker equalization case demonstrate the usage of the tool. The
output ".txt" files will be possible to apply with alsactl to setup
the equalizers in SOF.
> SOFT: Add equalizer tuning scripts and small examples

- kmod_scripts/sof_bootloop.sh
- kmod_scripts/sof_bootone.sh
Make sure DMA trace overflow are filtered out, and conversely trap IPC timeout errors which are quite frequent. Also stop the bootloop when a problem is hit.
> Enhance kmod scripts

- tune/eq/eq_compute.m
- tune/eq/eq_defaults.m
- tune/eq/eq_define_parametric_eq.m
- tune/eq/eq_iir_blob_quant.m
- tune/eq/eq_norm.m
- tune/eq/eq_plot.m
- tune/eq/example_fir_eq.m
- tune/eq/example_iir_eq.m
- tune/eq/example_spk_eq.m
This first part of of this patch set mainly updates compatibility of equalizers tuning and setup scripts with Matlab. Previously IIR design failed totally in Matlab with incorrect non-stable designs due to difference in parameters of bilinear transform function. There is still after this an issue hitting Matlab (but not Octave) in some IIR designs. The issue in tf2sos() poles and zeros mapping to biquads needs more work to fix. Until that it's recommended to do IIR designs only with Octave.
The second part cleans up the example designs and improves the result of speaker example.
> Update EQ tune scripts

- topology/sof/pipe-src-playback.m4
This patch decreases pipeline buffers usage from 5x or 4x periods to 3x
to avoid DAI error in APL platform when allocating buffers. The smaller
buffers are sufficient since the test topology pipelines are scheduled
every 1ms (earlier assumption was every 5 ms).
The PCM capability is updated to 8 channels similarly as with low delay
pipeline. The highest sample rate is increased from 96 kHz to 192 kHz.
> Decrease SRC pipeline buffers RAM size and update PCM configuration

- topology/Makefile.am
- topology/sof-apl-wm8804.m4
This SPDIF transmitter/receiver is used by the HifiBerry DIGI+ and
DIGI IO. The wm8804 operates as bit clock and frame master.
TODO in future update: add support for capture on the DIGI+ IO (this
may be done with a different topology file to avoid confusing users
with a non-working PCM capture patch)
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> topology: add support for wm8804

- test/src_run.sh
- test/src_test.m
This patch fixes the command line sample rate parameters passing
into host testbench (-r & -R).
In my computer at least the print command of non-visible plots stopped
working into error so I disabled the print commant that creates PNG
graphics files. It's OK since the purpose of this script is batch testing.
The visible plot files can be enabled from SRC test script to see plots
if need for deep dive.
The patch includes also fix for text output for "help src_test". The
input and output word lengths were missing from sample command.
> SRC test: Fix testbench execute command line plus cleanup

- topology/Makefile.am
- topology/m4/Makefile.am
- topology/m4/hda.m4
- topology/sof-apl-hdmi.m4
This is v3 series for PR#54.
Add a new hda.m4 that defines macro HDA_DAI_CONFIG(idx, link_id, name) for user to define configurations for HDA Backend links.
Defines a new file sof-apl-hdmi.m4 for 3 HDMI HDA links. Verified on LeafHill.
History:
v2: Use a separate file hda.m4 to define HDA stuff, instead of in existing dai.m4, as Liam suggested.
v3: Renamed sof-apl-hda.m4 to sof-apl-hdmi.m4 because it only contains 3 playback pipelines for HDMI/DP audio. Revised pipeline IDs to start from 1 and be continuous for easy maintaining.
> v3 topology: Add suppport for HDA links

- topology/m4/dai.m4
- topology/m4/debug.m4
- topology/m4/pipeline.m4
- topology/m4/utils.m4
- topology/sof-apl-da7219.m4
- topology/sof-apl-pcm512x.m4
This is a first try to produce some useful info for users hacking with m4 topology.
There's a new file debug.m4 with couple of simple macros to output data. These are used from dai_add, pcm_add, and graph creation.
Debug macros are using errprint to print to stderr, so you could differentiate between actual macro output and debug messaging. To get the graph printing correct, you need to surround your m4 with DEBUG_START and DEBUG_END. You can see examples in sof-apl-pcm512x.m4 and sof-apl-da7219.m4
There are currently 2 debug defines, GRAPH and INFO. GRAPH produces dot file describing the topology graph connection. INFO produces diagnostic messages mainly concerned with dai indexing.
You can invoke the debugging like this:
m4 -I m4 -I common -I platform/common --define=GRAPH …
> [RFC] topology: first try of m4 debug macros

- topology/sof-glk-da7219.m4
Define 3 new PCMs and backends for HDMI/DP playback on GLK platform.
Here are the updated pipelines in sof-glk-da7219.m4:
PCM0  ----> volume (pipe 1)   ---> SSP1 (speaker - maxim98357a, BE link 0)
PCM1  <---> volume (pipe 2,3) <--> SSP2 (headset - da7219, BE link 1)
PCM99 <---- volume (pipe 4)   <--- DMIC0 (dmic capture, BE link 2)
PCM5  ----> volume (pipe 5)   ---> iDisp1 (HDMI/DP playback, BE link 3)
PCM6  ----> Volume (pipe 6)   ---> iDisp2 (HDMI/DP playback, BE link 4)
PCM7  ----> volume (pipe 7)   ---> iDisp3 (HDMI/DP playback, BE link 5)
There is also support for changing HDMI/DP pipelines to pass-through for
validation purpose, which is commented off by default.
Pleaes note that 3 virtual widgets hifi1~3 are removed, because they'll
be created by HDMI codec driver. This m4 was …
> topology: Add 3 HDMI/DP PCMs and backends for GLK

- tune/eq/eq_tplg_write.m
- tune/eq/example_fir_eq.m
- tune/eq/example_iir_eq.m
- tune/eq/example_spk_eq.m
This patch adds export function for the m4 syntax bytes data and adds
the export of such blob to example designs. The example EQ designs are
edited to make this format export too.
In addition the example FIR length is adjusted to be near current IPC
length maximum (384) and improve the effect quality.
> EQ Tool: Output topology m4 binary control style configuration data

- tune/eq/eq_fir_blob_quant.m
This patch adds removing of extra zeros in the FIR coefficients. The
zeros can happen in some responses due to fixed point quantization of
very small values. The zero taps consume DSP resources for nothing so
better to clean them out for EQ configuration data.
> EQ FIR: Add check and removal for trailing zeros in filter coefficients

- topology/sof-glk-da7219.m4
Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>
> topology: sof-glk-da7219: update to use s32le format for HDMI pipelines

- Makefile.am
- configure.ac
- logger/Makefile.am
- logger/logger.c
I've added tool for parsing new trace format.
As input tool gets two files:
1) extracted .static_log_entries section generated by rimage in file *ldc (sof\src\arch\xtensa\*ldc) - this rimage feature is added in #418 PR in sof repository;
2) binary file containing catch trace from dma.
Tool throws parsed logs to stdout.
> Logger: added tool for parsing new trace format

- eqctl/eqctl.c
Fixes seg faults when input file does not exist.
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
> eqctl: do not process invalid input file name

- topology/sof/pipe-eq-fir-volume-playback.m4
- topology/sof/pipe-eq-iir-volume-playback.m4
- topology/sof/pipe-eq-volume-playback.m4
Pipelines should not expose more channels than what they are configured
to support.
Signed-off-by: Curtis Malainey <cujomalainey@google.com>
> Use passed in number of channels for pipeline

- tune/eq/eq_tplg_write.m
This patch updates the export format to currently used format in
topology. It adds also possibility to pass text comment into line
above the bytes from EQ design script. The date is appended
automatically after comment.
> EQ tune: Update m4 format EQ filter coefficients syntax

- rmbox/convert.h
- rmbox/logger_convert.c
- rmbox/rmbox.c
Signed-off-by: ArturX Kloniecki <arturx.kloniecki@linux.intel.com>
> logger: Implement possibility to read log data from stdin

- test/test_utils/mls_calc_resp.m
- tune/eq/mls_freq_resp.m
- tune/eq/mls_play_config.txt
- tune/eq/mls_rec_config.txt
This patch adds into SOFT/tune/eq a script mls_freq_resp.m that can
be used as low budget or quick developer tool to measure device frequency
response. The configuration files mls_play_config.txt and
mls_rec_config.txt configure the audio devices for local or remote
ssh aplay/arecord execution.
The MLS measurement with a short time window, e.g. less than 10 ms can
partially achieve the same as anechoic measurement. However this
is not intended to replace usage any professional audio measurement. If
using this use with care!
Note also that as such this script measures the response of a
speaker - microphone system. One response need to be known and
under calibration to get reliable results for other. Even ADC and DAC
responses may impact.
Signed-off-by: Seppo Ingalsuo …
> EQ: Add tool for acoustical frequency response measurement

- topology/sof-apl-pcm512x.m4
Add HDMI support to sof-apl-pcm512x
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>
> topology: enable hdmi support on UP2 board

- tune/eq/eq_iir_blob_pack.m
This patch adds explicit conversion to signed int32 type for response to
channels indices in assign_response and filter coefficients. The bug was
visible if trying to activate in IIR blob the per channel filter bypass
by having a negative value (-1) in any of channel assigns. Octave assumed
the type to be unsigned and produced wrong configuration bytes.
The filter coefficients are already integer type from previous
quantization code in the conversion process. However it does not hurt to
have extra safety to avoid similar issue as assign.
> EQ: Fix an integer type bug in IIR coefficients blob packer

- rmbox/logger_convert.c
- rmbox/rmbox.c
Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>
> rmbox: fix rmbox KW issues

- rmbox/Makefile.am
- rmbox/rmbox.c
Change binary names:
- from logger to sof-logger
- from rmbox to sof-rmbox
Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>
> rmbox: change binary names of logger and rmbox

- eqctl/eqctl.c
This patch adds the missed details into the code.
> eqctl: Add check for calloc() success and return 0 in exit

- topology/m4/pipeline.m4
In PIPELINE_PCM_ADD, DAI_FORMAT is not set but are used later.
Need to set this value to avoid protenial issues.
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>
> topology: duplicate dai formart for pcm add

- topology/Makefile.am
- topology/sof-apl-dmic-2ch.m4
- topology/sof-apl-dmic-4ch.m4
This patch adds two minimal capture topologies to enable doing tests
those require raw audio capture with unmodified S32_LE samples, e.g.
channels order preserve test where the mic # origin can be checked
from side information in LSB bits.
> Topology: Add 2ch and 4ch raw DMIC capture topologies for APL

- test/audio/src_run.sh
- test/audio/src_test.m
The directories were restructured lately and this patch fixes the
changed paths issue.
> Test: Audio: Fix paths in SRC host version testbench

- rmbox/logger_convert.c
In case of getting invalid trace address file descriptor
now moves forward only one dword, not whole struct dma_log
as it was earlier.
Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>
> logger: refinement handling invalid trace address

- tune/eq/mls_freq_resp.m
- tune/eq/mls_rec_config.txt
This patch adds capability to apply for capture microphone calibration
data (ASCII text lines with Hz, dB values). The calibration data file
name needs to be edited into configuration file mls_rec_config.txt. Such
calibration data is provided by several inexpensive USB measurement
microphones manufacturers.
> EQ Tool: Add calibration data import

- topology/sof-glk-da7219.m4
Fix the channel count to 2 for stereo dmic recording.
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
> topology: glk: fix channel count for dmic stereo recording

- topology/Makefile.am
- topology/sof-icl-dmic-4ch.m4
Signed-off-by: Zhang Keqiao <keqiao.zhang@linux.intel.com>
> topology: add 4-ch dmic topology for ICL
